db:
  type: "oracle"
  host: "103.134.154.73"
  port: "1521"
  username: "system"
  password: "oracle"
  schema: "xe"
  conn:
    max-idle: "20"
    max-lifetime: "10m"
    keep-alive-interval: "5m"
    max-open: "100"
restapi:
  port: 6969
  request-timeout: 1h
  healthcheck-path: /health/info
  info-path: /actuator/info
  shutdown:
    wait-duration: 1s
    timeout-duration: 5s
jwt:
  key: "3WfPT*Zned"
  expired: 24h
  refresh_expired: 8766h
  key-otp: "token-otp"
  expired-otp: 1h
header:
  token-param: "token"
  refresh-token-param: "refresh-token"
  token-otp: "token-otp"
  reset-password-otp: "reset-password-token"
  all-language-param: "all-language"